export default {
    switch:[{
        label:'地图是否自动定位',
        value:true
    },{

    }],
    theme:[{
        label:'跟随系统',
        value:'default'
    },{
        label:'暗色',
        value:'dark'
    },{
        label:'md3-暗色',
        value:'md3-dark'
    },{
        label:'md3-亮色',
        value:'md3-light'
    }],
    fps:[30,60],
    data_source:[{
        label:'网路',
        value:'websocket'
    },{
        label:'usb',
        value:'serial'
    }]
}