/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./components/bottom-bar/index.vue')['default']
    Dev: typeof import('./components/dev/index.vue')['default']
    DevBinData: typeof import('./components/dev-bin-data/index.vue')['default']
    Map: typeof import('./components/map/index.vue')['default']
    MdIcon: typeof import('./components/md-icon/index.vue')['default']
    Popup: typeof import('./components/popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemSetting: typeof import('./components/system-setting/index.vue')['default']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
  }
}

// For TSX support
declare global {
  const BottomBar: typeof import('./components/bottom-bar/index.vue')['default']
  const Dev: typeof import('./components/dev/index.vue')['default']
  const DevBinData: typeof import('./components/dev-bin-data/index.vue')['default']
  const Map: typeof import('./components/map/index.vue')['default']
  const MdIcon: typeof import('./components/md-icon/index.vue')['default']
  const Popup: typeof import('./components/popup/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SystemSetting: typeof import('./components/system-setting/index.vue')['default']
  const VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
  const VarButton: typeof import('@varlet/ui')['_ButtonComponent']
  const VarDivider: typeof import('@varlet/ui')['_DividerComponent']
  const VarIcon: typeof import('@varlet/ui')['_IconComponent']
  const VarImage: typeof import('@varlet/ui')['_ImageComponent']
  const VarInput: typeof import('@varlet/ui')['_InputComponent']
}